# Generated by Django 4.1.4 on 2022-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ثبت شده', 'Set'), ('تمام', 'Done'), ('نیامد', 'Absent')], default='ثبت شده', max_length=50, verbose_name='وضعیت'),
        ),
    ]
